---
- name: set gpg key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: add repository
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main'
    filename: teams
    update_cache: no
    state: present

# Handle cache update on a dedicated task to cover the case where the
# repository was already added, but the cache was not updated. This also
# allows to move the cache update out of the package install task.
- name: APT cache updated
  apt:
    update_cache: yes
